
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 20;
  public static final int GE = 25;
  public static final int LPAREN = 21;
  public static final int SEMI = 23;
  public static final int REPEAT = 10;
  public static final int INT = 4;
  public static final int MINUS = 18;
  public static final int WRITE = 13;
  public static final int RPAREN = 22;
  public static final int LBLOCKPAREN = 28;
  public static final int LT = 15;
  public static final int COMMA = 32;
  public static final int UNTIL = 11;
  public static final int NUM = 34;
  public static final int PLUS = 17;
  public static final int ASSIGN = 14;
  public static final int IF = 2;
  public static final int ID = 33;
  public static final int LE = 24;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int error = 1;
  public static final int LCURLY = 30;
  public static final int NEQ = 27;
  public static final int VOID = 6;
  public static final int EQ = 26;
  public static final int ERROR = 35;
  public static final int RCURLY = 31;
  public static final int TIMES = 19;
  public static final int ELSE = 3;
  public static final int READ = 12;
  public static final int WHILE = 7;
  public static final int THEN = 8;
  public static final int END = 9;
  public static final int RBLOCKPAREN = 29;
  public static final int GT = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "THEN",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "ASSIGN",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LE",
  "GE",
  "EQ",
  "NEQ",
  "LBLOCKPAREN",
  "RBLOCKPAREN",
  "LCURLY",
  "RCURLY",
  "COMMA",
  "ID",
  "NUM",
  "ERROR"
  };
}

